### ISSUE TITLE
Cannot Login from Reeder

### ISSUE THREAD

**Issue by DrHilarious** [dasmurphy/tinytinyrss-fever-plugin#2]
I followed the instructions in the forum and yet cannot login. I transferred 1.4.4 into the plugins folder, enabled it in tt-rss, set my password, and attempted to login with the Reeder app, but it returns "Login Failed." My password is apparently incorrect, though I have made sure to set it to only three characters in order to eliminate the possibility of mis-typing it. I have retried about ten times to make sure I was typing the URL correctly, with the slash at the end and including the full http://www at the beginning, and once again without the www.

My directory is called "tinyrss" instead of "tt-rss" and is located in my www folder. Will this setup adversely affect my ability to use this plugin? Please advise.

Finally, thank you for writing this plugin. It is certainly going to help many transition from Google Reader.

**Comment by oit63** [comment]
Perfect！ I met this problem just now. and solve it by check the  'external API access', too. Thanks
