### ISSUE TITLE
Multiple accounts in Reeder

### ISSUE THREAD

**Issue by Zettt** [dasmurphy/tinytinyrss-fever-plugin#22]
Hello,

Is it possible to have multiple accounts in Reeder that point to the same installation, but obviously different logins? I'm not sure if Reeder can't handle that. I've set it up, but I had no luck so far. (I figured I ask here first, because I don't think Silvio is going to answer.)

Thank you!

**Comment by dasmurphy** [comment]
I only have Reeder on iOS. This works here.

**Important**: Don't forget to enable for each user the fever plugin and external api access. Also you need to set the password in the fever plugin. I you forget some of this, it will fail on authentication.

Hope this helps.

**Comment by Zettt** [comment]
Actually, no, it doesn't. Because you don't answer to the original question. ;-)

So, the following:

I have TT-RSS setup and I have the Fever plugin running. I have set up one account with it in Reeder and everything is working just fine. Now I want to add another Fever account to the same Reeder app. So I go to the settings and enter the same server URL, but this time giving it the account details from the second account. 

→ This causes an issue and I don't know who the culprit is. Is it the plugin or is it Reeder?

**Comment by dasmurphy** [comment]
That was i writing. I tested it on iOS Reeder and all works here with 2 accounts.

**Please read this carefully. This is important.**
In TTRSS you need to enable the api access in general settings, enable the fever plugin and set the password in the fever plugin. Every setting is user specific. So it is needed to be done on **all TTRSS users** in the web interface of TTRSS. You can do it with logging in of the specific user. After that you can add all accounts you need to Reeder. I only could test iOS.

So to answer your original question: Yes, Reeder on iOS is capable to use 2 accounts from one TTRSS installation. ;)

Does it help this time? :P If not, what issue was it causing?

**Comment by Zettt** [comment]
Yea, I know. I've done all of that. Reeder tells me that the password or login is wrong on the second account. Guess it's a Reeder issue then. Oh well.

**Comment by dasmurphy** [comment]
Great to know. We will solve it somehow. Is it Reeder on Mac? I will try to get a version and debug it.

**Comment by Zettt** [comment]
I just tried it on iOS as well. Same issue. Asks me to provide the correct email or/and password. 
Here's some more information that might cause issues:
- The username of the second account start with a capital letter.
- TT-RSS is on a subdomain, e.g. `news.mydomain.com`. So the plugin adress is `news.mydomain.com/plugins/fever`.
- The password uses some special characters. Nothing too fancy like `ü` though.

**Comment by dasmurphy** [comment]
I've written the creator of Reeder 3 days ago for some help. No reply till now. Hope he is supporting me here a little bit. Thumbs up!

**Comment by dasmurphy** [comment]
Did you solve it?

**Comment by Zettt** [comment]
I did. I ended up deleting the second account, creating a new one and it worked just fine.

**Comment by dasmurphy** [comment]
Perfect.

**Comment by CoderSherlock** [comment]
Also in to the same issue.
