### ISSUE TITLE
Unable to login with Reeder

### ISSUE THREAD

**Issue by menzbua** [dasmurphy/tinytinyrss-fever-plugin#34]
Hi,

i've installed Tiny Tiny RSS with the fever API plugin on my server.
I'm unable to connect to the Fever API with Reeder on my Mac. Fallowing i've done already:

- API access is enabled
- Fever password is enabled
- When I visit .../ttrss/plugins/fever/ I see {"api_version":3,"auth":0}

When i enable the debug i just get on line when i try to login:

parameter: {"api":"","api_key":"md5sum"}

I've checked the api_key with the value in the database for the user and it matches. Now i don't know what i can do to enable the feature.

Thanks

Regards
Manuel

**Comment by rogierlommers** [comment]
Try miniflux, a better alternative.
Op di 23 jan. 2018 om 17:21 schreef menzbua <notifications@github.com>

**Comment by kdvy** [comment]
You essentially want to replace fever_api.php with the contents of : https://raw.githubusercontent.com/dzaikos/tinytinyrss-fever-plugin/f024cdcfba91f2f69f1e93a9c1c4b5b3574905df/fever/fever_api.php

See: #33 

Miniflux-legacy appears to support fever. Miniflux 2 doesn't.

**Comment by rogierlommers** [comment]
Miniflux2 DOES support fever out-of-the-box. It's very actively developed at the moment. I really suggest you should give it a try.

**Comment by menzbua** [comment]
I'm already switched to Miniflux. It works fine with fever-api.

Regards
Manuel

**Comment by kun-neulion** [comment]
Ahh.. apologies - I see it now in the docs. Will try it out thanks.

**Comment by kdvy** [comment]
Apologies. I see it now in the docs. Will try it out. Thanks!
