### ISSUE TITLE
Uncaught Error: Class 'CCache' not found

### ISSUE THREAD

**Issue by jeffery9876** [dasmurphy/tinytinyrss-fever-plugin#36]
IP: 37.156.74.110Request URI: /plugins.local/fever/?apiUser agent: Reeder/4020.29.01 CFNetwork/1126 Darwin/19.5.0 (x86_64)

E_ERROR (1) | plugins.local/fever/fever_api.php:780 | Uncaught Error: Class 'CCache' not found in /var/www/ttrss/plugins.local/fever/fever_api.php:780 Stack trace: #0 /var/www/ttrss/plugins.local/fever/fever_api.php(790): FeverAPI->setItem() #1 /var/www/ttrss/plugins.local/fever/fever_api.php(936): FeverAPI->setItemAsRead() #2 /var/www/ttrss/plugins.local/fever/fever_api.php(911): FeverAPI->markId() #3 /var/www/ttrss/plugins.local/fever/index.php(70): FeverAPI->index() #4 {main} thrown

**Comment by dasmurphy** [comment]
Sorry, this version of the PHP plugin does not work with the current version. Currently i have no time to update it.

Try this one: https://github.com/cdoenges/tinytinyrss-fever-plugin

It has a fix that i'm not having.
